// Code/Front End/React-DappUI/src/MemoryDappUI/ViewSubmission/ViewSubmission.js
import React from 'react';
import ipfsService from '../../services/IPFSService';
import './ViewSubmission.css';

export default class ViewSubmission extends React.Component {
  constructor(props){
    super(props);
    this.onSubmit = this.onSubmit.bind(this);
    this.state = {
      isDirty: false
    };
  }

  async onSubmit(event){
    event.preventDefault();

    const request = {
      hash: this.submissionId.value
    };

    try{
        const response = await ipfsService.getJSON(request);
        console.log(response);
    }catch(reason){
        console.log(reason);
    }
  }

  onChange = (event) => {
    if(event.target.value !== ''){
      this.setState({isDirty: true});
    }
  }

  render(){
    return (
      <form onSubmit={this.onSubmit} className="form-container">
        <div className="form-group">
          <label htmlFor="name">Enter Submission ID or IPFS Hash</label>
          <input
            type="text"
            className="form-control"
            ref={node => (this.submissionId = node)}
            placeholder="Enter Submision ID or IPFS Hash"
            onChange={this.onChange}
          />
        </div>

        <input
          type="submit"
          className="btn btn-primary pull-right"
          value="View Submission"
          disabled={!this.state.isDirty}
        />
      </form>
    );
  }
}

// Code/Front End/DappUI/src/memoryDappUI/view-submission/view-submission.component.ts
import { Component, OnInit } from '@angular/core';
import { IPFSService } from '../../shared/services/IPFS/ipfs.service';
import { FormGroup, FormControl, Validators } from '@angular/forms';
import { SubmissionResponse } from '../../shared/Models/Ethereum/SubmissionResponse';
import { SubmissionRequest } from '../../shared/Models/Ethereum/SubmissionRequest';
import { SubmissionService } from '../../shared/services/submission/submission.service';
import { IPFSGetResponse } from '../../shared/Models/IPFS/IPFSGetResponse';

@Component({
  selector: 'app-view-submission',
  templateUrl: './view-submission.component.html',
  styleUrls: ['./view-submission.component.css']
})
export class ViewSubmissionComponent implements OnInit {
  _formGroup: FormGroup;
  Submissions: IPFSGetResponse[];

  constructor(private _submissionService: SubmissionService) {
       this.Submissions = [];
   }

  ngOnInit() {
      this._formGroup = new FormGroup({
          submissionId: new FormControl('',{ validators: [Validators.required, Validators.pattern('^[0-9]*$')] })
      });
  }

  async viewMemory(event:any) {
      const request: SubmissionRequest = new SubmissionRequest();
      request.submisionId = +this._formGroup.get('submissionId').value;
      let response: IPFSGetResponse = await this._submissionService.getSubmission(request);
      this.Submissions.length = 0;
      this.Submissions.push(response);
  }

  isValid(): boolean {
      return this._formGroup.valid;
  }

}

<div class="container">
  <form [formGroup]="_formGroup">
    <div class="form-group">
      <label for="submissionId">Enter Submission Id</label>
      <input type="number"
             id="submissionId"
             formControlName="submissionId"
             class="form-control"
      />
    </div>

    <button type="button"
              class="btn btn-primary pull-right"
              id="viewMemoryBtn"
              [disabled]="!isValid()"
              (click)="viewMemory($event)">View Memory
    </button>
  </form>

  <br>
  <submissions [Submissions] = "Submissions"></submissions>
</div>
